# This is a basic workflow to help you get started with Actions

name: Download and combine data

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 6 * * *
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - combine.pl
      - .github/workflows/combine.yml
      - leeds-city-region/leeds.csv

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: JSON::XS

      # Runs script
      - name: Run validator script
        working-directory: .
        run: |
          perl combine.pl
      - name: Commit changes to files
        working-directory: .
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add leeds-city-region/combined.csv
          git commit -m "Update validation" || exit 0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
